# Generated by Django 5.2.7 on 2025-11-06 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_teammember_tasks_task_assignee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='manager_id',
            new_name='manager',
        ),
    ]
